name: Auto database update
on:
  schedule:
    - cron: '24 21,23 * * Tue,Wed,Fri,Sat'
  workflow_dispatch:
jobs:
  release:
    name: latest version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: install dependencies
        run: npm i
      - name: update
        run: npm run updatedb
      - name: test
        run: npm run test
      - name: commit
        run: script/auto-update.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GTOKEN}}
